// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydpspkxgrdclihvsvruh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkcHNwa3hncmRjbGlodnN2cnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzMDUxNjAsImV4cCI6MjA4MTg4MTE2MH0.wU6DUQbKHg2YZYjSZ0ZuYeBiFjgvIQAQdduSZVLpU8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
